[versions]
agp = "8.10.1"
kotlin = "2.0.21"
jna = "5.16.0"

[libraries]
jna = { group = "net.java.dev.jna", name = "jna", version.ref = "jna" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
rustandroid = { id = "org.mozilla.rust-android-gradle.rust-android", version = "0.9.6" }
