[package]
name = "androidvpnrust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "androidvpnrust"

[[bin]]
name = "uniffi-bindgen"
path = "src/uniffi-bindgen.rs"

[profile.release]
strip = "debuginfo"
lto = true

[dependencies]
proton-vpn-binary-status = { registry = "proton-public", version = "1.0.0", features = ["uniffi"] }
protun = { path = "../protun/", features = ["uniffi", "android"], optional = true }
uniffi = { version = "0.29", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.29", features = ["build"] }

[features]
protun = ["dep:protun"]